### ISSUE TITLE
znc-playback sending messages before requested time

### ISSUE THREAD

**Issue by kylef** [jpnurmi/znc-playback#5]
ZNC-Playback is reliably re-sending me the last message, the `[from]` component of the PLAY command seems to be inclusive not exclusive of the message already seen.

#### First Connection

I receive the following message"

```
S: @time=2017-04-21T12:07:17.129Z :nick!ident@host PRIVMSG #channel :Hello
```

The `Hello` message contains the time `2017-04-21T12:07:17.129Z` which is `1492776437.129` as epoch time.

#### New Connection

I make a new connection and ask for the buffers since my last known message `2017-04-21T12:07:17.129Z` or `1492776437.129`.

```
C: PRIVMSG *playback :PLAY #channel 1492776437.129
S: @time=2017-04-21T12:29:53.277Z :znc.in BATCH +aa9ea93a831b97650935cacf685882b8 znc.in/playback #channel
S: @batch=aa9ea93a831b97650935cacf685882b8;time=2017-04-21T12:07:17.129Z :nick!ident@host PRIVMSG #channel :Hello
S: @time=2017-04-21T12:29:53.277Z :znc.in BATCH -aa9ea93a831b97650935cacf685882b8
```

Note, I have received the previous message again causing duplication.

**Comment by strugee** [comment]
@kylef is there a reason you've closed this? Is the issue fixed?

**Comment by strugee** [comment]
@kylef is there a reason you've closed this? Is the issue fixed?
